# Week 6 worksheet: More containers and sequences

This week, we introduce **tuples** and **dictionaries**, two other types of *container* available in Python. We also introduce **comprehensions** as a concise way to create lists, and the related concepts of **iterables and generators**.

The best way to learn programming is to write code. Don't hesitate to edit the code in the example cells, or add your own code, to test your understanding. You will find practice exercises throughout the notebook, denoted by 🚩 ***Exercise $x$:***.

#### Displaying solutions

Solutions will be released one week after the worksheets are released, as a new `.txt` file in the same GitHub repository. After pulling the file to your workspace (either your computer or your Noteable server), run the following cell to create clickable buttons under each exercise, which will allow you to reveal the solutions.

In [ ]:
%run scripts/create_widgets.py week06

---
## Comprehensions

Comprehensions are a nice feature of Python not found in many other languages. In a sense they are a combination of sequence, for loop and if statement. They allow us to construct a new sequence from an old sequence, doing some operation for each element of the original sequence. Here is an example:

In [3]:
square_numbers = [1,4,9,16,25]
square_plus1 = [x+1 for x in square_numbers]
print(square_plus1)

[2, 5, 10, 17, 26]


The general syntax for them is 

```python
[expression for item in seq if condition]                   # if
[expression1 if condition else expression2 for item in seq] # if-else
```

Comprehensions can make your code more compact and readable.

---
🚩 ***Exercise 1:*** Try to write the following loop in one line with a list comprehension.

In [1]:
#  In the sequence n**2+3 for n = 50 to 100, find the numbers which are divisors of 6
factors6 = []
for n in range(50,101):
    if (n**2 + 3) % 6 == 0:
        factors6.append(n**2 + 3)
        
print(factors6)

[2604, 3252, 3972, 4764, 5628, 6564, 7572, 8652, 9804]


In [ ]:
%run scripts/show_solutions.py week06_ex1

---
Comprehensions can be **nested** in one another as well. Look at the example below where the prime numbers less than 100 are generated with one nested list comprehension:

In [18]:
primes = [x for x in range(2,100) if not [t for t in range(2,x) if not x%t]]
print(primes)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


- The inner comprehension builds a list of all the factors of `x`, since `not x%t` is `True` when `x` is divisible by `t`. It gives an empty list if `x` doesn't have any factors (i.e. if `x` is prime).
- The outer comprehension builds a list by selecting the numbers `x` up to 100 for which the inner list is empty (since `not []` is `True`)-- i.e. the numbers `x` which are prime.

Here is another example: building and flattening matrices using nested comprehensions.

In [36]:
import numpy as np

# Build the identity matrix
I = np.array([[1 if i==j else 0 for i in range(4)] for j in range(4)])
print(f'I =\n{I}\n')

# Flatten a matrix to a list -- here, "i" is a list of the rows of A
A = np.random.randint(1, 10, size=[3, 3])
print(f'A =\n{A}\n')
print([j for i in A for j in i])

I =
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

A =
[[4 1 6]
 [9 4 3]
 [5 6 8]]

[4, 1, 6, 9, 4, 3, 5, 6, 8]
[array([4, 1, 6]), array([9, 4, 3]), array([5, 6, 8])]


---
🚩 ***Exercise 2:*** In one line, using comprehensions, create a list of all 24 possible (ordered) combinations of the characters `a`, `b`, `c` which are not triplets. For instance, you list should contain `'aab'` and `'cba'`, but not `'bbb'`.

In [ ]:
%run scripts/show_solutions.py week06_ex2

---
## Tuples

**Tuples** share similarities with lists; an important difference is that tuples are **immutable** --- that is, you cannot change its elements after it is defined. A tuple can be created by typing a sequence of values separated by a comma, surrounded by round brackets `(...)`. For example,
```
a = (4, 6, -2, 4, 0, 0)
```
We can access elements or subsequences of a tuple using indexing and slicing, just as for lists. Many of the functions and some of the operators we have used to operate on lists can also be used with tuples. For example:

In [31]:
a = (4, 6, -2, 4, 0, 0)     # A tuple of numbers
b = ()                      # An empty tuple
c = (2, 2, (-4, 5), 2)      # A nested tuple
d = (0.1, 'that', 2)        # Tuples can also contain mixed data
e = (8,)                    # A tuple with 1 element -- note the trailing comma!

# We can nest tuples in lists...
f = [(1, 2), (), e, ('this', 'maybe')]

# ... and lists in tuples
g = ([3, 4], [3], 0, [0.122, -0.1])

# Indexing and slicing also work on tuples
print('Indexing:')
print(a[2:])
print(g[3][0])
print(f[:3])

# Some functions we can use...
print('\nFunctions:')
print(len(d))
print(sorted(a))        # Note that sorted() still returns a list!
print(tuple(sorted(a))) # Casting a list to a tuple
print(list(d))          # Casting a tuple to a list

# And some operators...
print('\nOperators:')
print(d + c)
print((2, -0.33) * 5)
print(e in f)

Indexing:
(-2, 4, 0, 0)
0.122
[(1, 2), (), (8,)]

Functions:
3
[-2, 0, 0, 4, 4, 6]
(-2, 0, 0, 4, 4, 6)
[0.1, 'that', 2]

Operators:
(0.1, 'that', 2, 2, 2, (-4, 5), 2)
(2, -0.33, 2, -0.33, 2, -0.33, 2, -0.33, 2, -0.33)
True


A useful feature is that variables can be **unpacked** from a tuple, meaning that we can, for example, assign the value of each element in a tuple to a different variable, in one line:

In [49]:
u, v, w = (3.4, 1, 'friday')
print(f'{u}, {w}')

# Swap 2 values
u, w = w, u
print(f'{u}, {w}')

3.4, friday
friday, 3.4


This is what you do when you write a function which returns multiple output values -- in reality, it returns one tuple containing the output values.

---
**Note:** Lists, tuples, and strings are examples of **sequences**, meaning that their elements (for a `str`, its characters) are *ordered*, and indexed by a number representing their position. Index slicing can also be used on any sequence type.

---
**📚 Learn more:**
* [Tuples and Sequences - Python 3.7 documentation](https://docs.python.org/3/tutorial/datastructures.html?highlight=lists#tuples-and-sequences)
* [Sequence types: list, tuple, range - Python 3.7 documentation](https://docs.python.org/3/library/stdtypes.html#sequence-types-list-tuple-range)
---


## Dictionaries

A Python **dictionary** is a set of ***key-value* pairs**. Each value is indexed by a distinct key, which may be a number, a string, or a tuple of numbers or strings. (In contrast, each value in a list or a tuple is indexed by a positive integer, corresponding to its position.) Dictionary values can be any object (e.g. numbers, sequences, booleans, even other nested dictionaries).

A dictionary can be created from a comma-separated list of `key: value` pairs, surrounded by curly brackets `{}`, for example

In [33]:
scores = {'Alice': 80, 'Bob': 64, 'Charlie': 72}
print(scores['Bob'])

64


<div style="width:70%;margin:auto;">

| `scores = {'Alice': 80, 'Bob': 64, 'Charlie': 72}` |
|:--:|
| ![The dictionary scores in memory](graphics/dict.png) |

</div>

Dictionaries are useful to hold data which it doesn't make sense to index by number -- here, for example, it's much easier to keep track of the students' grades if they're indexed with their name, instead of some arbitrary integer number.

The following *dictionary methods* allow you to access the elements of a dictionary in different ways. Make sure to run the cell above beforehand to define the `scores` dictionary.

In [34]:
print(scores)                # Print the dictionary object
print(list(scores.items()))  # Print dict items as a list of tuples
print(list(scores.keys()))   # Print all keys in a list
print(list(scores.values())) # Print all values in a list

{'Alice': 80, 'Bob': 64, 'Charlie': 72}
[('Alice', 80), ('Bob', 64), ('Charlie', 72)]
['Alice', 'Bob', 'Charlie']
[80, 64, 72]


We can add and modify dictionary entries, or check whether a *key* exists in a dictionary:

In [35]:
# Create an empty dictionary
my_dict = {}

# Add 3 new items -- note that we don't need to append with dictionaries
my_dict['First item'] = (4, 5)
my_dict['Second item'] = 'blue'
my_dict[(0, 1)] = True
print(my_dict)
print(len(my_dict))

# Modify one item
my_dict['Second item'] = 8.77
print(my_dict)

# Check if a key (not a value!) exists in the dictionary
print((0, 1) in my_dict)
print((4, 5) in my_dict)

{'First item': (4, 5), 'Second item': 'blue', (0, 1): True}
3
{'First item': (4, 5), 'Second item': 8.77, (0, 1): True}
True
False


---
**📚 Learn more:**
* [Dictionaries - Python 3.7 documentation](https://docs.python.org/3/tutorial/datastructures.html?highlight=lists#dictionaries) - introduction and some examples.
* [Mapping types - Dictionary - Python 3.7 documentation](https://docs.python.org/3/library/stdtypes.html#typesmapping) - includes a list of operations which dictionaries support.
---

🚩 ***Exercise 3:*** The dictionary `grades` below contains the grades that 3 students, Alice, Bob, and Charlie, obtained so far this semester in their school subjects. Complete the code (without touching the first 3 lines!) to:
- update Alice's maths grade to a B, and
- add a new C grade in English for Charlie,
- add grades for a new student, Dara, with a B in maths and a D in history.

In [50]:
grades = {'Alice': {'maths': 'A', 'english': 'C', 'music': 'B'},
          'Bob': {'maths': 'C', 'english': 'A', 'history': 'A'},
          'Charlie': {'physics': 'D', 'music': 'A', 'biology': 'A'}}



In [ ]:
%run scripts/show_solutions.py week06_ex3

#### Looping over dictionaries

A convenient way to loop over a dictionary uses the `.items()` method to return a list of tuples.

In [54]:
months_length = {'January': 31, 'February': 28, 'March': 31 ,'April': 30,
                 'May': 31 ,'June': 30, 'July': 31, 'August': 31, 'September': 30,
                 'October': 31, 'November': 30, 'December': 31}

out = 'The months of '

for month, duration in months_length.items():
    if duration == 31:
        out = out + month + ', '

out = out + 'have 31 days.'
print(out)

The months of January, March, May, July, August, October, December, have 31 days.


---
🚩 ***Exercise 4:*** Build a new dictionary `grades_by_subject` by looping over `grades` (from Exercise 3), where the keys are the different subjects in `grades` and the values are nested dictionaries, where the keys are the students' names and the values are the grades.

In [ ]:
%run scripts/show_solutions.py week06_ex4

---

## Iterables and iterators

**Iterables** in Python are the technical name for anything that has an **order** and can be enumerated. For instance, when we make a loop `for ... in ...`, the sequence we are looping over is an iterable.
- Some of the examples of iterables that we have seen so far are lists, strings, tuples, and ranges.
- On the other hand, for example, `float`, `bool`, or `int` are not iterables (try starting a loop with `for i in 5:` and watch the error message!)

**Iterators** are value producers which yield successive values from their associated iterable. In simple words, they are like bookmarks: whenever we call them, they return the value of a particular element of the iterable they are associated with, and then move the bookmark to the next element. The next time we call them, they pick the new element and move the bookmark forward again.  

Below we create a list of powers of two using a list comprehension, and then create an iterator associated with this list using the function `iter()`. Once you created your iterator, you can call the function `next()` on it, and it yields the value of the element that your iterator is pointing at, and moves the bookmark forward. Next time you call `next()`, you get a next element of your list.

In [60]:
# create the list of powers of 2 from 1 to 2**12
powers_two = [2**n for n in range(12)]
print(powers_two)

# create an iterator associated with 'powers_two'
my_iter = iter(powers_two)

# starting from the beginning call your iterator, see what happens
print(next(my_iter))
print(next(my_iter))

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048]
1
2


In the follwoing loop, we try to pick the rest of the values of `powers_two`, from where it was left off.  

In [61]:
for i in range(10):
    print(f'iteration number {i}, and iterator is returning {next(my_iter)}')

iteration number 0, and iterator is returning 4
iteration number 1, and iterator is returning 8
iteration number 2, and iterator is returning 16
iteration number 3, and iterator is returning 32
iteration number 4, and iterator is returning 64
iteration number 5, and iterator is returning 128
iteration number 6, and iterator is returning 256
iteration number 7, and iterator is returning 512
iteration number 8, and iterator is returning 1024
iteration number 9, and iterator is returning 2048


What will happen if you call `next()` one more time? Does the error make sense to you?

In [63]:
print(next(my_iter))

StopIteration: 

The advantage of iterators is that they don't need to occupy too much memory, because they only need to keep track of where they are and then how to generate the next value (as opposed to keeping all the values in the iterables like lists)!

---
**📚 Learn more:**

- [Iterators](https://docs.python.org/3/tutorial/classes.html#iterators) - The Python tutorial

From the Python documentation:
- [The `iter` object](https://docs.python.org/3/glossary.html#term-iterator)
- [Iterator](https://docs.python.org/3/glossary.html#term-iterator)
- [`next()`](https://docs.python.org/3/library/functions.html#next)
- [`StopIteration` exception](https://docs.python.org/3/library/exceptions.html#StopIteration)

---

## Generators

Another object type that is closely related to iterators is the **generator**. Generators can be counted as one of the strengths of Python relative to other programming languages that don't have this feature.

Generators are a way of defining a procedure to get the next number in a sequence. They can remember where they were left off in a sequence, and generate the next number each time they are called. To understand them let's consider the *infinite* sequence of square numbers

$$
{1,\ 4,\ 9,\ 16,\ 25,\ ...,\ n^2,\ ...}
$$

Using functions and lists, we cannot produce an infinite sequence. At best we can write a function that takes an argument $N$ as an input and returns a list of square numbers up to $N^2$. This is not ideal! We want an object that can remember what the last square number it calculated was, and then generate the next square number the next time we call it. In this way, we have no limitation on the number of times we call this sequence producer (and we don't take up much memory). The beloved object that can manage to do this for us is **generator**.


To define a generator, we write something that looks a little like a function, but instead of the `return` keyword we use `yield` to give a result from the generator.

Note that each time a function reaches `return` statement, it returns its output and the compiler completely forgets what values were stored inside the function variables. Next time we call the function, it starts from the beginning and does not remember anything from the last time it was called. A generator is very different though:
- The first time it is called (using `next()`), it starts from the beginning and executes commands until it reaches the first `yield` statement. At this point, it stops and yields the value.
- The second time it is called, it starts from the previous `yield` statement and continues executing commands until it reaches the next `yield` statement. Then it stops again and yields the new value.
- This procedure goes on each time we call the generator.

In the example below we create the infinite sequence of square numbers and examine it:

In [71]:
def squares_func():
    num = 1
    while True:
        yield num**2
        num += 1

# squares_func is a generator function:
print(type(squares_func))

# But the output of squares_func is a generator iterator:
squares_gen = squares_func()
print(type(squares_gen))

print('First for-loop:')
for i in range(5):
    print(f'My square number is {next(squares_gen)}')
    

# Do other things in the code
print('\nI am doing other things...')

print(f'\nI am printing the next square number after the first for-loop: {next(squares_gen)}')

print('\nSecond for-loop:')
for i in range(5):
    print(f'My square number is {next(squares_gen)}')

<class 'function'>
<class 'generator'>
First for-loop:
My square number is 1
My square number is 4
My square number is 9
My square number is 16
My square number is 25

I am doing other things...

I am printing the next square number after the first for-loop: 36

Second for-loop:
My square number is 49
My square number is 64
My square number is 81
My square number is 100
My square number is 121


Generators can be a very memory efficient way to deal with a problem - a list is all stored in memory, but a generator is made as you go, you don’t have to store the whole thing at once.

---
**📚 Learn more:**

- [Generators](https://docs.python.org/3/tutorial/classes.html#generators) - The Python tutorial
- [generator, generator iterator](https://docs.python.org/3/glossary.html#term-generator) - The Python glossary
- [Yield expressions](https://docs.python.org/3/reference/expressions.html#yieldexpr) - Python documentation

---
🚩 ***Exercise 5:*** In mathematics, the Perrin numbers are defined by the recurrence relation

$$
P(n) = P(n − 2) + P(n − 3), \quad n > 2,
$$
with initial values
$$
P(0) = 3, P(1) = 0, P(2) = 2.
$$

Following this relation, the sequence of Perrin numbers starts with

3, 0, 2, 3, 2, 5, 5, 7, 10, 12, 17, 22, 29, 39, ...

Write a generator that produces an infinite sequence of Perrin numbers.

In [ ]:
%run scripts/show_solutions.py week06_ex5